#!/usr/bin/env python3
"""Download Billboard 200 Year-End Top Albums (2015-2024)"""

import asyncio
import sys
import time
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))

from tidal_tui import TidalAPI, DownloadManager, Track

# Billboard 200 Year-End Top Albums (Artist, Album Title)
# Top 100 albums per year
BILLBOARD_TOP_ALBUMS = {
    2024: [
        ("Taylor Swift", "The Tortured Poets Department"),
        ("Beyonce", "Cowboy Carter"),
        ("Sabrina Carpenter", "Short n' Sweet"),
        ("Billie Eilish", "Hit Me Hard and Soft"),
        ("Chappell Roan", "The Rise and Fall of a Midwest Princess"),
        ("SZA", "SOS"),
        ("Morgan Wallen", "One Thing at a Time"),
        ("Noah Kahan", "Stick Season"),
        ("Ariana Grande", "Eternal Sunshine"),
        ("Olivia Rodrigo", "GUTS"),
        ("Zach Bryan", "The Great American Bar Scene"),
        ("Post Malone", "F-1 Trillion"),
        ("Tyler, The Creator", "Chromakopia"),
        ("Kendrick Lamar", "GNX"),
        ("Travis Scott", "Utopia"),
        ("21 Savage", "American Dream"),
        ("Future & Metro Boomin", "We Don't Trust You"),
        ("Dua Lipa", "Radical Optimism"),
        ("Charli XCX", "BRAT"),
        ("The Weeknd", "The Highlights"),
        ("Drake", "For All the Dogs"),
        ("Taylor Swift", "1989 (Taylor's Version)"),
        ("Taylor Swift", "Lover"),
        ("Taylor Swift", "Midnights"),
        ("Eminem", "The Death of Slim Shady"),
        ("Tate McRae", "Think Later"),
        ("Bad Bunny", "Nadie Sabe Lo Que Va a Pasar Manana"),
        ("Peso Pluma", "Exodus"),
        ("Benson Boone", "Fireworks & Rollerblades"),
        ("Luke Combs", "Fathers & Sons"),
        ("Gunna", "A Gift & A Curse"),
        ("Metro Boomin", "Heroes & Villains"),
        ("Lana Del Rey", "Did You Know That There's a Tunnel Under Ocean Blvd"),
        ("Nicki Minaj", "Pink Friday 2"),
        ("Jelly Roll", "Beautifully Broken"),
        ("NewJeans", "Get Up"),
        ("Karol G", "Manana Sera Bonito"),
        ("Doja Cat", "Scarlet"),
        ("Chris Stapleton", "Higher"),
        ("Stray Kids", "5-STAR"),
        ("Hozier", "Unreal Unearth"),
        ("Miley Cyrus", "Endless Summer Vacation"),
        ("Ed Sheeran", "Subtract"),
        ("Metallica", "72 Seasons"),
        ("Taylor Swift", "Speak Now (Taylor's Version)"),
        ("Olivia Rodrigo", "SOUR"),
        ("The Weeknd", "After Hours"),
        ("Kanye West", "Vultures 1"),
        ("Zach Bryan", "Zach Bryan"),
        ("Stray Kids", "Rock-Star"),
    ],
    2023: [
        ("Morgan Wallen", "One Thing at a Time"),
        ("Taylor Swift", "Midnights"),
        ("SZA", "SOS"),
        ("Drake", "For All the Dogs"),
        ("Travis Scott", "Utopia"),
        ("Taylor Swift", "Speak Now (Taylor's Version)"),
        ("Taylor Swift", "1989 (Taylor's Version)"),
        ("Olivia Rodrigo", "GUTS"),
        ("Zach Bryan", "Zach Bryan"),
        ("Luke Combs", "Gettin' Old"),
        ("Ed Sheeran", "Subtract"),
        ("Bad Bunny", "Un Verano Sin Ti"),
        ("Metro Boomin", "Heroes & Villains"),
        ("Morgan Wallen", "Dangerous: The Double Album"),
        ("Taylor Swift", "Lover"),
        ("The Weeknd", "The Highlights"),
        ("Peso Pluma", "Genesis"),
        ("Jung Kook", "Golden"),
        ("Noah Kahan", "Stick Season"),
        ("Lana Del Rey", "Did You Know That There's a Tunnel Under Ocean Blvd"),
        ("21 Savage", "American Dream"),
        ("Gunna", "A Gift & A Curse"),
        ("Doja Cat", "Scarlet"),
        ("Miley Cyrus", "Endless Summer Vacation"),
        ("Karol G", "Manana Sera Bonito"),
        ("Drake & 21 Savage", "Her Loss"),
        ("The Weeknd", "After Hours"),
        ("Chris Stapleton", "Higher"),
        ("Jelly Roll", "Whitsitt Chapel"),
        ("Olivia Rodrigo", "SOUR"),
        ("NewJeans", "Get Up"),
        ("Metallica", "72 Seasons"),
        ("Jason Aldean", "Highway Desperado"),
        ("Stray Kids", "5-STAR"),
        ("Lil Durk", "Almost Healed"),
        ("Seventeen", "FML"),
        ("Nicki Minaj", "Pink Friday 2"),
        ("Hozier", "Unreal Unearth"),
        ("Bailey Zimmerman", "Religiously. The Album."),
        ("Post Malone", "Austin"),
        ("Dua Lipa", "Future Nostalgia"),
        ("Harry Styles", "Harry's House"),
        ("Nicki Minaj", "Queen"),
        ("Future", "I Never Liked You"),
        ("Coldplay", "Music of the Spheres"),
        ("The Rolling Stones", "Hackney Diamonds"),
        ("Lil Baby", "It's Only Me"),
        ("Rod Wave", "Nostalgia"),
        ("Tate McRae", "Think Later"),
        ("Peso Pluma & Eslabón Armado", "Ella Baila Sola"),
    ],
    2022: [
        ("Harry Styles", "Harry's House"),
        ("Bad Bunny", "Un Verano Sin Ti"),
        ("Taylor Swift", "Midnights"),
        ("Drake", "Honestly, Nevermind"),
        ("Morgan Wallen", "Dangerous: The Double Album"),
        ("Beyonce", "Renaissance"),
        ("Olivia Rodrigo", "SOUR"),
        ("Future", "I Never Liked You"),
        ("The Weeknd", "The Highlights"),
        ("Adele", "30"),
        ("Dua Lipa", "Future Nostalgia"),
        ("Luke Combs", "This One's for You"),
        ("Lil Baby", "It's Only Me"),
        ("Gunna", "DS4EVER"),
        ("Post Malone", "Twelve Carat Toothache"),
        ("Taylor Swift", "Lover"),
        ("The Weeknd", "After Hours"),
        ("Drake & 21 Savage", "Her Loss"),
        ("Metro Boomin", "Heroes & Villains"),
        ("Jack Harlow", "Come Home the Kids Miss You"),
        ("Kendrick Lamar", "Mr. Morale & The Big Steppers"),
        ("Rod Wave", "Beautiful Mind"),
        ("Morgan Wallen", "If I Know Me"),
        ("Lil Durk", "7220"),
        ("Taylor Swift", "Red (Taylor's Version)"),
        ("Bad Bunny", "El Ultimo Tour Del Mundo"),
        ("Taylor Swift", "evermore"),
        ("Glass Animals", "Dreamland"),
        ("Coldplay", "Music of the Spheres"),
        ("YoungBoy Never Broke Again", "The Last Slimeto"),
        ("Chris Stapleton", "Starting Over"),
        ("Zach Bryan", "American Heartbreak"),
        ("BTS", "Proof"),
        ("Taylor Swift", "folklore"),
        ("Luke Combs", "Growin' Up"),
        ("Kodak Black", "Kutthroat Bill: Vol. 1"),
        ("Steve Lacy", "Gemini Rights"),
        ("Kane Brown", "Different Man"),
        ("Elvis Presley", "Elvis (Soundtrack)"),
        ("Doja Cat", "Planet Her"),
        ("The Weeknd", "Starboy"),
        ("Moneybagg Yo", "A Gangsta's Pain"),
        ("Tyler, The Creator", "Call Me If You Get Lost"),
        ("Arctic Monkeys", "AM"),
        ("Seventeen", "Face the Sun"),
        ("Nicki Minaj", "Queen"),
        ("NBA YoungBoy", "Colors"),
        ("SZA", "Ctrl"),
        ("Zac Brown Band", "The Comeback"),
        ("Bailey Zimmerman", "Leave the Light On"),
    ],
    2021: [
        ("Morgan Wallen", "Dangerous: The Double Album"),
        ("Olivia Rodrigo", "SOUR"),
        ("Dua Lipa", "Future Nostalgia"),
        ("Drake", "Certified Lover Boy"),
        ("The Weeknd", "After Hours"),
        ("The Weeknd", "The Highlights"),
        ("Pop Smoke", "Shoot for the Stars Aim for the Moon"),
        ("Taylor Swift", "evermore"),
        ("Taylor Swift", "folklore"),
        ("Ariana Grande", "Positions"),
        ("Kanye West", "Donda"),
        ("Lil Baby", "My Turn"),
        ("Luke Combs", "What You See Is What You Get"),
        ("Doja Cat", "Planet Her"),
        ("Bad Bunny", "El Ultimo Tour Del Mundo"),
        ("Billie Eilish", "Happier Than Ever"),
        ("Adele", "30"),
        ("The Kid Laroi", "F*CK LOVE (OVER YOU)"),
        ("Taylor Swift", "Red (Taylor's Version)"),
        ("Rod Wave", "SoulFly"),
        ("Lil Durk", "The Voice"),
        ("J. Cole", "The Off-Season"),
        ("Moneybagg Yo", "A Gangsta's Pain"),
        ("Luke Combs", "This One's for You"),
        ("Chris Stapleton", "Starting Over"),
        ("Justin Bieber", "Justice"),
        ("Taylor Swift", "Lover"),
        ("Polo G", "Hall of Fame"),
        ("Tyler, The Creator", "Call Me If You Get Lost"),
        ("Juice WRLD", "Legends Never Die"),
        ("BTS", "BE"),
        ("Megan Thee Stallion", "Good News"),
        ("Silk Sonic", "An Evening with Silk Sonic"),
        ("Giveon", "When It's All Said and Done"),
        ("Doja Cat", "Hot Pink"),
        ("Migos", "Culture III"),
        ("Drake", "Scorpion"),
        ("SZA", "Ctrl"),
        ("Morgan Wallen", "If I Know Me"),
        ("YoungBoy Never Broke Again", "Sincerely, Kentrell"),
        ("Coldplay", "Music of the Spheres"),
        ("Taylor Swift", "1989"),
        ("Ed Sheeran", "="),
        ("Glass Animals", "Dreamland"),
        ("Lil Nas X", "Montero"),
        ("The Weeknd", "Starboy"),
        ("H.E.R.", "Back of My Mind"),
        ("Rauw Alejandro", "Vice Versa"),
        ("Jazmine Sullivan", "Heaux Tales"),
        ("Taylor Swift", "Fearless (Taylor's Version)"),
    ],
    2020: [
        ("Lil Baby", "My Turn"),
        ("Pop Smoke", "Shoot for the Stars Aim for the Moon"),
        ("The Weeknd", "After Hours"),
        ("Taylor Swift", "folklore"),
        ("Juice WRLD", "Legends Never Die"),
        ("Taylor Swift", "evermore"),
        ("Bad Bunny", "YHLQMDLG"),
        ("Roddy Ricch", "Please Excuse Me for Being Antisocial"),
        ("Luke Combs", "What You See Is What You Get"),
        ("Post Malone", "Hollywood's Bleeding"),
        ("Bad Bunny", "El Ultimo Tour Del Mundo"),
        ("Lil Uzi Vert", "Eternal Atake"),
        ("Ariana Grande", "Positions"),
        ("Future", "High Off Life"),
        ("Travis Scott", "Astroworld"),
        ("Billie Eilish", "When We All Fall Asleep, Where Do We Go?"),
        ("Eminem", "Music to Be Murdered By"),
        ("Drake", "Scorpion"),
        ("YoungBoy Never Broke Again", "38 Baby 2"),
        ("Megan Thee Stallion", "Good News"),
        ("Dua Lipa", "Future Nostalgia"),
        ("The Weeknd", "Starboy"),
        ("BTS", "Map of the Soul: 7"),
        ("Polo G", "The Goat"),
        ("Lil Wayne", "Funeral"),
        ("DaBaby", "Blame It on Baby"),
        ("Morgan Wallen", "If I Know Me"),
        ("21 Savage", "Savage Mode II"),
        ("Gunna", "WUNNA"),
        ("Lady Gaga", "Chromatica"),
        ("Joyner Lucas", "Evolution"),
        ("Halsey", "Manic"),
        ("BTS", "Be"),
        ("YoungBoy Never Broke Again", "Top"),
        ("Doja Cat", "Hot Pink"),
        ("Queen", "Greatest Hits"),
        ("The Weeknd", "Beauty Behind the Madness"),
        ("Luke Combs", "This One's for You"),
        ("Mac Miller", "Circles"),
        ("Nav", "Good Intentions"),
        ("Rod Wave", "Pray 4 Love"),
        ("Harry Styles", "Fine Line"),
        ("Moneybagg Yo", "Time Served"),
        ("Lil Durk", "Just Cause Y'all Waited 2"),
        ("SAINt JHN", "While the World Was Burning"),
        ("A Boogie wit da Hoodie", "Artist 2.0"),
        ("Summer Walker", "Over It"),
        ("BTS", "Map of the Soul: Persona"),
        ("Tory Lanez", "Daystar"),
        ("Bob Marley & The Wailers", "Legend"),
    ],
    2019: [
        ("Billie Eilish", "When We All Fall Asleep, Where Do We Go?"),
        ("Post Malone", "Hollywood's Bleeding"),
        ("Travis Scott", "Astroworld"),
        ("Drake", "Scorpion"),
        ("Ariana Grande", "Thank U, Next"),
        ("Khalid", "Free Spirit"),
        ("Juice WRLD", "Death Race for Love"),
        ("Tyler, The Creator", "IGOR"),
        ("Queen", "Bohemian Rhapsody"),
        ("Luke Combs", "This One's for You"),
        ("A Boogie wit da Hoodie", "Hoodie SZN"),
        ("Meek Mill", "Championships"),
        ("Taylor Swift", "Lover"),
        ("Ariana Grande", "Sweetener"),
        ("Lil Baby", "Street Gossip"),
        ("Offset", "Father of 4"),
        ("The Greatest Showman", "Soundtrack"),
        ("Gunna", "Drip or Drown 2"),
        ("DaBaby", "Baby on Baby"),
        ("Young Thug", "So Much Fun"),
        ("Lil Nas X", "7"),
        ("Ed Sheeran", "÷"),
        ("Bad Bunny", "X 100PRE"),
        ("Kodak Black", "Dying to Live"),
        ("21 Savage", "I Am > I Was"),
        ("Panic! At The Disco", "Pray for the Wicked"),
        ("Halsey", "Manic"),
        ("Cardi B", "Invasion of Privacy"),
        ("Chris Brown", "Indigo"),
        ("Rod Wave", "Ghetto Gospel"),
        ("Summer Walker", "Over It"),
        ("Chance the Rapper", "The Big Day"),
        ("Luke Combs", "What You See Is What You Get"),
        ("YoungBoy Never Broke Again", "AI YoungBoy 2"),
        ("Lizzo", "Cuz I Love You"),
        ("J. Cole", "KOD"),
        ("Logic", "Confessions of a Dangerous Mind"),
        ("Migos", "Culture II"),
        ("Lil Tecca", "We Love You Tecca"),
        ("Elton John", "Rocketman"),
        ("Lil Durk", "Love Songs 4 the Streets 2"),
        ("PnB Rock", "TrapStar Turnt PopStar"),
        ("Lil Baby & Gunna", "Drip Harder"),
        ("Lil Uzi Vert", "Luv Is Rage 2"),
        ("YNW Melly", "We All Shine"),
        ("Post Malone", "Beerbongs & Bentleys"),
        ("Morgan Wallen", "If I Know Me"),
        ("Rick Ross", "Port of Miami 2"),
        ("Quality Control", "Control the Streets, Volume 2"),
        ("Maren Morris", "GIRL"),
    ],
    2018: [
        ("Drake", "Scorpion"),
        ("Travis Scott", "Astroworld"),
        ("Post Malone", "Beerbongs & Bentleys"),
        ("XXXTentacion", "?"),
        ("The Greatest Showman", "Soundtrack"),
        ("Ariana Grande", "Sweetener"),
        ("Cardi B", "Invasion of Privacy"),
        ("Migos", "Culture II"),
        ("Eminem", "Kamikaze"),
        ("Post Malone", "Stoney"),
        ("J. Cole", "KOD"),
        ("Lil Wayne", "Tha Carter V"),
        ("Ella Mai", "Ella Mai"),
        ("Travis Scott", "Birds in the Trap Sing McKnight"),
        ("Panic! At The Disco", "Pray for the Wicked"),
        ("XXXTentacion", "17"),
        ("Ed Sheeran", "÷"),
        ("6ix9ine", "Day69"),
        ("Migos", "Culture"),
        ("Logic", "Bobby Tarantino II"),
        ("Juice WRLD", "Goodbye & Good Riddance"),
        ("21 Savage", "I Am > I Was"),
        ("Meek Mill", "Championships"),
        ("A Star Is Born", "Soundtrack"),
        ("Taylor Swift", "Reputation"),
        ("Khalid", "American Teen"),
        ("Nicki Minaj", "Queen"),
        ("Mac Miller", "Swimming"),
        ("Luke Combs", "This One's for You"),
        ("Lil Baby", "Harder Than Ever"),
        ("YoungBoy Never Broke Again", "Until Death Call My Name"),
        ("Brockhampton", "Iridescence"),
        ("Gunna", "Drip Season 3"),
        ("Kodak Black", "Dying to Live"),
        ("Drake", "More Life"),
        ("A Boogie wit da Hoodie", "Hoodie SZN"),
        ("Queen", "Bohemian Rhapsody"),
        ("SZA", "Ctrl"),
        ("Nas", "Nasir"),
        ("Teyana Taylor", "K.T.S.E."),
        ("Lil Pump", "Lil Pump"),
        ("Lil Skies", "Life of a Dark Rose"),
        ("Nipsey Hussle", "Victory Lap"),
        ("The Weeknd", "Starboy"),
        ("Future", "Beast Mode 2"),
        ("Rich the Kid", "The World Is Yours"),
        ("Black Panther", "The Album"),
        ("Lil Xan", "Total Xanarchy"),
        ("BlocBoy JB", "Simi"),
        ("Chris Brown", "Heartbreak on a Full Moon"),
    ],
    2017: [
        ("Ed Sheeran", "÷"),
        ("Drake", "More Life"),
        ("Kendrick Lamar", "DAMN."),
        ("The Weeknd", "Starboy"),
        ("Post Malone", "Stoney"),
        ("21 Savage", "Issa Album"),
        ("Migos", "Culture"),
        ("Future", "Future"),
        ("Big Sean", "I Decided"),
        ("Metallica", "Hardwired...to Self-Destruct"),
        ("Future", "Hndrxx"),
        ("Drake", "Views"),
        ("Bruno Mars", "24K Magic"),
        ("Kodak Black", "Painting Pictures"),
        ("Lil Uzi Vert", "Luv Is Rage 2"),
        ("Nav", "NAV"),
        ("J. Cole", "4 Your Eyez Only"),
        ("Migos", "Culture II"),
        ("Post Malone", "Beerbongs & Bentleys"),
        ("Travis Scott", "Birds in the Trap Sing McKnight"),
        ("JAY-Z", "4:44"),
        ("Logic", "Everybody"),
        ("The Weeknd", "Beauty Behind the Madness"),
        ("Tyler, The Creator", "Flower Boy"),
        ("DJ Khaled", "Grateful"),
        ("The Chainsmokers", "Memories...Do Not Open"),
        ("Moana", "Soundtrack"),
        ("A Boogie wit da Hoodie", "The Bigger Artist"),
        ("Young Thug", "Beautiful Thugger Girls"),
        ("Playboi Carti", "Playboi Carti"),
        ("Sam Hunt", "Montevallo"),
        ("XXXTentacion", "17"),
        ("Meek Mill", "Wins & Losses"),
        ("Khalid", "American Teen"),
        ("Lil Yachty", "Teenage Emotions"),
        ("Machine Gun Kelly", "Bloom"),
        ("Taylor Swift", "Reputation"),
        ("Chris Stapleton", "From A Room: Volume 1"),
        ("Bryson Tiller", "True to Self"),
        ("SZA", "Ctrl"),
        ("Lorde", "Melodrama"),
        ("Wiz Khalifa", "Rolling Papers 2"),
        ("Luke Combs", "This One's for You"),
        ("Imagine Dragons", "Evolve"),
        ("Gucci Mane", "DropTopWop"),
        ("PnB Rock", "Catch These Vibes"),
        ("Zayn", "Mind of Mine"),
        ("Gorillaz", "Humanz"),
        ("Trey Songz", "Tremaine the Album"),
        ("Rick Ross", "Rather You Than Me"),
    ],
    2016: [
        ("Drake", "Views"),
        ("Beyonce", "Lemonade"),
        ("The Weeknd", "Starboy"),
        ("Post Malone", "Stoney"),
        ("Frank Ocean", "Blonde"),
        ("DJ Khaled", "Major Key"),
        ("Ariana Grande", "Dangerous Woman"),
        ("Rihanna", "Anti"),
        ("Kanye West", "The Life of Pablo"),
        ("J. Cole", "4 Your Eyez Only"),
        ("Adele", "25"),
        ("Twenty One Pilots", "Blurryface"),
        ("Metallica", "Hardwired...to Self-Destruct"),
        ("A Tribe Called Quest", "We Got It from Here... Thank You 4 Your Service"),
        ("Travis Scott", "Birds in the Trap Sing McKnight"),
        ("Chance the Rapper", "Coloring Book"),
        ("Sia", "This Is Acting"),
        ("Future", "Evol"),
        ("Zayn", "Mind of Mine"),
        ("Radiohead", "A Moon Shaped Pool"),
        ("Justin Bieber", "Purpose"),
        ("The Weeknd", "Beauty Behind the Madness"),
        ("Anderson .Paak", "Malibu"),
        ("Suicide Squad", "The Album"),
        ("Jeremih", "Late Nights"),
        ("YG", "Still Brazy"),
        ("Mac Miller", "The Divine Feminine"),
        ("Kid Cudi", "Passion, Pain & Demon Slayin'"),
        ("Fifth Harmony", "7/27"),
        ("Lil Wayne", "Collegrove"),
        ("Schoolboy Q", "Blank Face LP"),
        ("Kendrick Lamar", "untitled unmastered."),
        ("Gucci Mane", "Everybody Looking"),
        ("Blake Shelton", "If I'm Honest"),
        ("Chris Stapleton", "Traveller"),
        ("Kevin Gates", "Islah"),
        ("Tory Lanez", "I Told You"),
        ("Isaiah Rashad", "The Sun's Tirade"),
        ("Young Thug", "Jeffery"),
        ("Desiigner", "New English"),
        ("Bon Iver", "22, A Million"),
        ("Green Day", "Revolution Radio"),
        ("Yo Gotti", "The Art of Hustle"),
        ("Dave East", "Kairi Chanel"),
        ("Childish Gambino", "Awaken, My Love!"),
        ("Solange", "A Seat at the Table"),
        ("Tegan and Sara", "Love You to Death"),
        ("Meghan Trainor", "Thank You"),
        ("Blink-182", "California"),
        ("Red Hot Chili Peppers", "The Getaway"),
    ],
    2015: [
        ("Adele", "25"),
        ("Drake", "If You're Reading This It's Too Late"),
        ("The Weeknd", "Beauty Behind the Madness"),
        ("Taylor Swift", "1989"),
        ("Fetty Wap", "Fetty Wap"),
        ("Drake & Future", "What a Time to Be Alive"),
        ("Meek Mill", "Dreams Worth More Than Money"),
        ("Justin Bieber", "Purpose"),
        ("Big Sean", "Dark Sky Paradise"),
        ("Future", "DS2"),
        ("Ed Sheeran", "x"),
        ("Meghan Trainor", "Title"),
        ("Sam Smith", "In the Lonely Hour"),
        ("Chris Stapleton", "Traveller"),
        ("J. Cole", "2014 Forest Hills Drive"),
        ("Twenty One Pilots", "Blurryface"),
        ("A$AP Rocky", "At. Long. Last. A$AP"),
        ("Nicki Minaj", "The Pinkprint"),
        ("Drake", "Nothing Was the Same"),
        ("Travi$ Scott", "Rodeo"),
        ("Lil Wayne", "Sorry 4 the Wait 2"),
        ("Dr. Dre", "Compton"),
        ("Kendrick Lamar", "To Pimp a Butterfly"),
        ("Future", "56 Nights"),
        ("Jason Aldean", "Old Boots, New Dirt"),
        ("Luke Bryan", "Kill the Lights"),
        ("The Weeknd", "Trilogy"),
        ("Future", "Monster"),
        ("Mumford & Sons", "Wilder Mind"),
        ("Fall Out Boy", "American Beauty/American Psycho"),
        ("Ariana Grande", "My Everything"),
        ("Hozier", "Hozier"),
        ("Trey Songz", "Trigga"),
        ("Kevin Gates", "Luca Brasi 2"),
        ("Imagine Dragons", "Smoke + Mirrors"),
        ("Rich Homie Quan", "If You Ever Think I Will Stop Goin' In Ask RR"),
        ("Ellie Goulding", "Delirium"),
        ("Ludacris", "Ludaversal"),
        ("Jeezy", "Church In These Streets"),
        ("Lana Del Rey", "Honeymoon"),
        ("Macklemore & Ryan Lewis", "This Unruly Mess I've Made"),
        ("Tyler, The Creator", "Cherry Bomb"),
        ("Alabama Shakes", "Sound & Color"),
        ("G-Eazy", "When It's Dark Out"),
        ("Vince Staples", "Summertime '06"),
        ("Tove Lo", "Queen of the Clouds"),
        ("The Game", "The Documentary 2"),
        ("Zac Brown Band", "Jekyll + Hyde"),
        ("Young Thug", "Barter 6"),
        ("Carrie Underwood", "Storyteller"),
    ],
}


async def main():
    print("=== DOWNLOADING BILLBOARD 200 TOP ALBUMS (2015-2024) ===\n")
    print("10 years × ~50 albums = ~500 albums\n")
    print("This will download thousands of tracks!\n")

    api = TidalAPI()
    download_manager = DownloadManager()
    await download_manager.connect()

    all_tracks = []
    total_found_albums = 0
    total_missed_albums = 0
    total_tracks_found = 0

    for year in sorted(BILLBOARD_TOP_ALBUMS.keys(), reverse=True):
        albums = BILLBOARD_TOP_ALBUMS[year]
        print(f"\n[{year}] Searching for {len(albums)} albums...")
        year_albums = 0
        year_tracks = 0

        for i, (artist, album_title) in enumerate(albums):
            # Search for the album
            query = f"{artist} {album_title}"
            try:
                album_results = await api.search_albums(query, limit=3)

                if album_results:
                    # Take the first result
                    album = album_results[0]

                    # Get all tracks from the album
                    tracks = await api.get_album_tracks(album.id, album)

                    if tracks:
                        all_tracks.extend(tracks)
                        year_albums += 1
                        year_tracks += len(tracks)
                        total_tracks_found += len(tracks)

                        if (i + 1) % 10 == 0:
                            print(f"  [{i+1}/{len(albums)}] {album.title} by {album.artist} ({len(tracks)} tracks)")
                    else:
                        total_missed_albums += 1
                else:
                    total_missed_albums += 1
                    if total_missed_albums <= 10:
                        print(f"  [!] Not found: {artist} - {album_title}")

            except Exception as e:
                total_missed_albums += 1
                if total_missed_albums <= 10:
                    print(f"  [!] Error: {artist} - {album_title}: {e}")

            # Small delay to avoid rate limiting
            await asyncio.sleep(0.1)

        total_found_albums += year_albums
        print(f"  {year}: Found {year_albums}/{len(albums)} albums ({year_tracks} tracks)")

    print(f"\n=== SEARCH COMPLETE ===")
    print(f"Albums found: {total_found_albums}")
    print(f"Albums missed: {total_missed_albums}")
    print(f"Total tracks: {len(all_tracks)}")

    if all_tracks:
        print(f"\nAdding {len(all_tracks)} tracks to queue...")
        added = download_manager.add_tracks(all_tracks)
        print(f"Added: {added} tracks (skipped {len(all_tracks) - added} duplicates/existing)")

        if added > 0:
            print(f"\n=== STARTING DOWNLOAD ({added} tracks) ===")
            download_manager.stats.session_start = time.time()
            download_manager.stats.session_bytes = 0

            # Start downloads
            await download_manager.download_all()

            final_stats = download_manager.get_stats()
            elapsed = time.time() - download_manager.stats.session_start

            print(f"\n=== DOWNLOAD COMPLETE ===")
            print(f"Completed: {final_stats['completed']}")
            print(f"Failed: {final_stats['failed']}")
            print(f"Total size: {final_stats['bytes']/1024/1024/1024:.2f} GB")
            print(f"Total time: {elapsed/60:.1f} minutes")
            print(f"Avg speed: {(final_stats['bytes']/1024/1024)/max(elapsed,1):.1f} MB/s")
        else:
            print("All tracks already downloaded!")
    else:
        print("No tracks found to download.")


if __name__ == "__main__":
    asyncio.run(main())
